### ISSUE TITLE
npm install error at mac el caption

### ISSUE THREAD

**Issue by yirius** [Geocent/node-hmd#4]
`CXX(target) Release/obj.target/hmd/src/binding.o
In file included from ../src/binding.cc:6:
../src/3rdparty/nan/nan.h:324:27: error: redefinition of 'NanEnsureHandleOrPersistent'
  NAN_INLINE v8::Local<T> NanEnsureHandleOrPersistent(const v8::Local<T> &val) {
                          ^
../src/3rdparty/nan/nan.h:319:17: note: previous definition is here
  v8::Handle<T> NanEnsureHandleOrPersistent(const v8::Handle<T> &val) {
                ^
../src/3rdparty/nan/nan.h:344:27: error: redefinition of 'NanEnsureLocal'
  NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Handle<T> &val) {
                          ^
../src/3rdparty/nan/nan.h:334:27: note: previous definition is here
  NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Local<T> &val) {
                          ^
../src/3rdparty/nan/nan.h:560:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback
      ~~~~~~~~~~~~~^
../src/3rdparty/nan/nan.h:566:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback) {
      ~~~~~~~~~~~~~^
../src/3rdparty/nan/nan.h:571:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback
      ~~~~~~~~~~~~~^
../src/3rdparty/nan/nan.h:577:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback) {
      ~~~~~~~~~~~~~^
../src/3rdparty/nan/nan.h:757:13: error: no member named 'smalloc' in namespace 'node'
    , node::smalloc::FreeCallback callback
      ~~~~~~^
../src/3rdparty/nan/nan.h:768:12: error: no matching function for call to 'New'
    return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
           ^~~~~~~~~~~~~~~~~
/Users/yangyuance1/.node-gyp/6.0.0/include/node/node_buffer.h:46:40: note: candidate function not viable: 2nd argument
      ('const char _') would lose const qualifier
NODE_EXTERN v8::MaybeLocalv8::Object New(v8::Isolate_ isolate,
                                       ^
/Users/yangyuance1/.node-gyp/6.0.0/include/node/node_buffer.h:34:40: note: candidate function not viable: no known
      conversion from 'const char _' to 'v8::Localv8::String' for 2nd argument
NODE_EXTERN v8::MaybeLocalv8::Object New(v8::Isolate_ isolate,
                                       ^
/Users/yangyuance1/.node-gyp/6.0.0/include/node/node_buffer.h:31:40: note: candidate function not viable: requires 2
      arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocalv8::Object New(v8::Isolate\* isolate, size_t length);
                                       ^
/Users/yangyuance1/.node-gyp/6.0.0/include/node/node_buffer.h:39:40: note: candidate function not viable: requires 5
      arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocalv8::Object New(v8::Isolate\* isolate,
                                       ^
In file included from ../src/binding.cc:6:
../src/3rdparty/nan/nan.h:772:12: error: no viable conversion from returned value of type 'v8::MaybeLocalv8::Object' to
      function return type 'v8::Localv8::Object'
    return node::Buffer::New(v8::Isolate::GetCurrent(), size);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/yangyuance1/.node-gyp/6.0.0/include/node/v8.h:216:7: note: candidate constructor (the implicit copy constructor)
      not viable: no known conversion from 'v8::MaybeLocalv8::Object' to 'const v8::Localv8::Object &' for 1st
      argument
class Local {
      ^
/Users/yangyuance1/.node-gyp/6.0.0/include/node/v8.h:216:7: note: candidate constructor (the implicit move constructor)
      not viable: no known conversion from 'v8::MaybeLocalv8::Object' to 'v8::Localv8::Object &&' for 1st argument
/Users/yangyuance1/.node-gyp/6.0.0/include/node/v8.h:220:13: note: candidate template ignored: could not match 'Local'
      against 'MaybeLocal'
  V8_INLINE Local(Local<S> that)
            ^
In file included from ../src/binding.cc:6:
../src/3rdparty/nan/nan.h:779:26: error: no member named 'Use' in namespace 'node::Buffer'
    return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
           ~~~~~~~~~~~~~~^
In file included from ../src/binding.cc:6:
In file included from ../src/3rdparty/nan/nan.h:24:
In file included from /Users/yangyuance1/.node-gyp/6.0.0/include/node/node.h:42:
/Users/yangyuance1/.node-gyp/6.0.0/include/node/v8.h:227:5: error: assigning to 'v8::Primitive *volatile' from
      incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/yangyuance1/.node-gyp/6.0.0/include/node/v8.h:186:37: note: expanded from macro 'TYPE_CHECK'
    _(static_cast<T_ volatile_>(0)) = static_cast<S_>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../src/3rdparty/nan/nan.h:501:12: note: in instantiation of function template specialization
      'v8::Localv8::Primitive::Localv8::Value' requested here
    return NanEscapeScope(NanNew(v8::Undefined(v8::Isolate::GetCurrent())));
           ^
../src/3rdparty/nan/nan.h:483:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(Nan::imp::NanEnsureLocal(val))

```
                         ^
```

In file included from ../src/binding.cc:6:
In file included from ../src/3rdparty/nan/nan.h:24:
In file included from /Users/yangyuance1/.node-gyp/6.0.0/include/node/node.h:42:
/Users/yangyuance1/.node-gyp/6.0.0/include/node/v8.h:227:5: error: assigning to 'v8::Boolean _volatile' from incompatible
      type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/yangyuance1/.node-gyp/6.0.0/include/node/v8.h:186:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T_ volatile_>(0)) = static_cast<S_>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../src/3rdparty/nan/nan.h:511:12: note: in instantiation of function template specialization
      'v8::Localv8::Boolean::Localv8::Value' requested here
    return NanEscapeScope(NanNew(v8::True(v8::Isolate::GetCurrent())));
           ^
../src/3rdparty/nan/nan.h:483:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(Nan::imp::NanEnsureLocal(val))

```
                         ^
```

In file included from ../src/binding.cc:6:
In file included from ../src/3rdparty/nan/nan.h:24:
In file included from /Users/yangyuance1/.node-gyp/6.0.0/include/node/node.h:42:
/Users/yangyuance1/.node-gyp/6.0.0/include/node/v8.h:227:5: error: assigning to 'v8::Function _volatile' from
      incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/yangyuance1/.node-gyp/6.0.0/include/node/v8.h:186:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T_ volatile_>(0)) = static_cast<S_>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../src/3rdparty/nan/nan.h:1627:12: note: in instantiation of function template specialization
      'v8::Localv8::Function::Localv8::Value' requested here
    return NanEscapeScope(NanNew(handle)->Get(kCallbackIndex)
           ^
../src/3rdparty/nan/nan.h:483:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(Nan::imp::NanEnsureLocal(val))

```
                         ^
```

In file included from ../src/binding.cc:6:
In file included from ../src/3rdparty/nan/nan.h:24:
In file included from /Users/yangyuance1/.node-gyp/6.0.0/include/node/node.h:42:
/Users/yangyuance1/.node-gyp/6.0.0/include/node/v8.h:227:5: error: assigning to 'v8::Object _volatile' from incompatible
      type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/yangyuance1/.node-gyp/6.0.0/include/node/v8.h:186:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T_ volatile_>(0)) = static_cast<S_>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../src/3rdparty/nan/nan.h:1747:12: note: in instantiation of function template specialization
      'v8::Localv8::Object::Localv8::Value' requested here
    return NanEscapeScope(handle->Get(NanNew(key)).Asv8::Object());
           ^
../src/3rdparty/nan/nan.h:483:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(Nan::imp::NanEnsureLocal(val))

```
                         ^
```

14 errors generated.
make: **\* [Release/obj.target/hmd/src/binding.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Darwin 15.4.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/yangyuance1/PhpstormProjects/oculus-nodejs-threejs-example/node_modules/node-hmd
gyp ERR! node -v v6.0.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "node-hmd" "--save"
npm ERR! node v6.0.0
npm ERR! npm  v3.9.0
npm ERR! code ELIFECYCLE

npm ERR! node-hmd@0.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-hmd@0.2.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-hmd package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-hmd
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-hmd
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/yangyuance1/PhpstormProjects/oculus-nodejs-threejs-example/`

pls help me

**Comment by carstenschwede** [comment]
Make sure you
- run **node 0.12** instead of **node 6.0**
- use `npm install Geocent/node-hmd.git` instead of `npm install node-hmd`
